### PR TITLE
Updated the README.md file to include the getting-started-help.md file.

### PR DESCRIPTION
**Pull request by akarsh**
Added `getting-started-help.md` file to the repository and updated the `README.md` file.

### CODE REVIEW

**Comment by akarsh** [comment]
Note: I thought the github pages would work. So I renamed the repository. But I found that it is not possible at the moment. So I am deploying it on vapor cloud deployment.

**Comment by akarsh** [comment]
I was finally able to deploy in vapor cloud.
Here is the link https://swiftdn.vapor.cloud

We need to decide if we can automate the deployment to vapor cloud. As currently I don't use any database. As this website will be static. If we get funding we can add database because database costs are associated with hosting in vapor cloud.

**Comment by brototyp** [comment]
Hi @akarsh, thanks a lot for this PR. There are a few things that I would like to mention.

* Can you please do me a favor and create an issue for the things you want to work on and explain what your goals are? This makes it much easier for me to reason about your changes.
* The `getting-started-help.md` is a great idea. There is a typo though 😊. `vapor xcocde` should be `vapor xcode`.
* The current state is not buildable, because I get a `/Sources/App/Models/Todo.swift:1:8: No such module 'FluentSQLite'` error.

About the GitHub Pages issue: Github pages only afaik only work if you have plain html or a [Jekyll](http://jekyllrb.com) based webpage.

**Comment by akarsh** [comment]
I made an issue #5  and explained the changes I made to this branch.

- I corrected the typo in this commit 

b53c79e 

- I removed the boiler plate code in this commit

24c97ab 

I did not know how to separate the commits of a single branch into multiple issues.

**Comment by brototyp** [comment]
Awesome. Thanks a lot.

**Pull request merged**
